; Meshtastic DIY v1 by Nano VHF Schematic based on ESP32-WROOM-32 (38 pins) devkit & EBYTE E22 SX1262/SX1268 module
[env:D_ESP32_E32_400M30S]
extends = esp32_base
board = esp32doit-devkit-v1
board_check = true
build_flags =
  ${esp32_base.build_flags}
  -D PRIVATE_HW
  -D OLED_UA
  -I variants/esp32/diy/D_ESP32_E32_400M30S

  -D MESHTASTIC_EXCLUDE_PAXCOUNTER=1
  -D MESHTASTIC_EXCLUDE_BATTERY=1
  -D MAX_NUM_NODES=100