[env:E22_400_MESH_V2]
extends = esp32s3_base
board = esp32-s3-zero
; board = esp32-s3-zero_2
; board = esp32-s3-fh4r2

build_flags = 
  ${esp32s3_base.build_flags}
  -I variants/esp32s3/E22_400_MESH_V2
  -D E32_MESH_V2
  -D PRIVATE_HW
  -D HW_VERSION=E22_400_MESH_V2
  -D OLED_UA

  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D BOARD_HAS_PSRAM
  ; -mfix-esp32-psram-cache-issue
  ; -D ENABLE_ROTARY_PULLUP
  ; -D ENABLE_BUTTON_PULLUP
  ; -D ROTARY_BUXTRONICS
  ; -D INPUTDRIVER_ROTARY_TYPE=1
  ; -D INPUTDRIVER_ROTARY_UP=4
  ; -D INPUTDRIVER_ROTARY_DOWN=42
  ; -D INPUTDRIVER_ROTARY_BTN=6
  ; -D INPUTDRIVER_BUTTON_TYPE=0


  ; АКТИВАЦИЯ КЛАВИАТУРЫ (Cardputer style)
  ; --- НАСТРОЙКИ КЛАВИАТУРЫ ---
  -D INPUTDRIVER_I2C_KBD          ; Включаем драйвер
  -D INPUTDRIVER_I2C_KBD_TYPE=1   ; TYPE 1 = CardKB (Адрес 0x5F, прерывание FALLING)
  ; --- ЗАГОТОВЛЕННЫЕ СООБЩЕНИЯ ---
  -D CANNED_MESSAGE_MODULE_ENABLE
  -D CANNED_MESSAGE_MODULE_ENABLE_KBD_SHORTCUTS 
  -D CANNED_MESSAGE_MODULE_KBD_SHORTCUTS_USE_FN_KEY
  
  -D GPS_POWER_TOGGLE ; comment this line to disable triple press function on the user button to turn off gps entirely.
  ; -D MESHTASTIC_EXCLUDE_PAXCOUNTER=1
  ; -D MESHTASTIC_EXCLUDE_BATTERY=1
  ; -D MAX_NUM_NODES=100

lib_deps =
  ${esp32s3_base.lib_deps}
  adafruit/Adafruit NeoPixel @ ^1.12.0