; Кастомная среда сборки для платы ProMicro с модемами Ebyte
[env:nrf52_promicro_ebyte_modems]
extends = nrf52840_base
board = promicro-nrf52840

; Добавляем путь к заголовочным файлам папки
build_flags = ${nrf52840_base.build_flags}
  -I variants/nrf52840/diy/nRF52840_Ebyte_modems
  -D NRF52_PROMICRO_DIY

; Указываем компилятору включить исходники папки в сборку
build_src_filter = ${nrf52_base.build_src_filter} +<../variants/nrf52840/diy/nRF52840_Ebyte_modems>

lib_deps = 
  ${nrf52840_base.lib_deps}
debug_tool = jlink
