; Власне середовище збірки для плати ProMicro з модемами Ebyte
[env:nrf52_promicro_ebyte_modems]
extends = nrf52840_base
board = promicro-nrf52840

; Додаємо шлях до заголовкових файлів папки
build_flags = ${nrf52840_base.build_flags}
  -I variants/nrf52840/diy/nRF52840_Ebyte_modems
  -D NRF52_PROMICRO_DIY
  ; Український шрифт OLED (кирилиця на екрані, розкладка UA клавіатури)
  -D OLED_UA

; Вказуємо компілятору включити вихідні файли папки у збірку
build_src_filter = ${nrf52_base.build_src_filter} +<../variants/nrf52840/diy/nRF52840_Ebyte_modems>

lib_deps = 
  ${nrf52840_base.lib_deps}
debug_tool = jlink
