; ESP32_TX_V2 - DIY board with E22-400M30S / E32-400M30S
; E22 (SX1268) active by default
[env:ESP32_TX_V2]
extends = esp32_base
board = esp32doit-devkit-v1
board_check = true
board_level = extra

build_flags =
  ${esp32_base.build_flags}
  -D PRIVATE_HW
  -D ESP32_TX_V2
  -D EBYTE_E22
  -D OLED_UA
  -I variants/esp32/diy/ESP32_TX_V2
  -D MESHTASTIC_EXCLUDE_PAXCOUNTER=1
  -D MESHTASTIC_EXCLUDE_BATTERY=1
  -D MAX_NUM_NODES=100