[env:E32_400_MESH_V2_keyboard] 
extends = esp32s3_base
board = esp32-s3-zero


build_flags = 
  ${esp32s3_base.build_flags}
  -I variants/esp32s3/E32_400_MESH_V2_keyboard
  -D E32_MESH_V2
  -D PRIVATE_HW
  -D OLED_UA
  ; -D HW_VERSION=E32_400_MESH_V2

  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MODE=1

  ; АКТИВАЦИЯ КЛАВИАТУРЫ (Cardputer style)
  ; --- НАСТРОЙКИ КЛАВИАТУРЫ ---
  -D INPUTDRIVER_I2C_KBD          ; Включаем драйвер
  -D INPUTDRIVER_I2C_KBD_TYPE=1   ; TYPE 1 = CardKB (Адрес 0x5F, прерывание FALLING)

  ; --- ЗАГОТОВЛЕННЫЕ СООБЩЕНИЯ ---
  -D CANNED_MESSAGE_MODULE_ENABLE
  -D CANNED_MESSAGE_MODULE_ENABLE_KBD_SHORTCUTS 
  -D CANNED_MESSAGE_MODULE_KBD_SHORTCUTS_USE_FN_KEY


  -D GPS_POWER_TOGGLE ; comment this line to disable triple press function on the user button to turn off gps entirely.
  ; -D MESHTASTIC_EXCLUDE_PAXCOUNTER=1
  ; -D MESHTASTIC_EXCLUDE_BATTERY=1
  ; -D MAX_NUM_NODES=100

lib_deps =
  ${esp32_base.lib_deps}
  adafruit/Adafruit NeoPixel @ ^1.12.0


